/*
* Generated file
*
* Generated from: yang module name: aaa-cassandra-store yang module local name: aaa-cassandra-store
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Nov 29 07:08:37 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.aaa.cassandra.store;
public class AAACassandraStoreModuleFactory extends org.opendaylight.controller.config.yang.config.aaa.cassandra.store.AbstractAAACassandraStoreModuleFactory {

}
