/*
* Generated file
*
* Generated from: yang module name: aaa-cassandra-store yang module local name: aaa-cassandra-store
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Nov 29 07:08:37 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.aaa.cassandra.store;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

public class AAACassandraStoreModuleFactory extends org.opendaylight.controller.config.yang.config.aaa.cassandra.store.AbstractAAACassandraStoreModuleFactory {
    @Override
    public AAACassandraStoreModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, AAACassandraStoreModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        AAACassandraStoreModule module =  super.instantiateModule(instanceName, dependencyResolver, oldModule, oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public AAACassandraStoreModule instantiateModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        AAACassandraStoreModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
