/*
* Generated file
*
* Generated from: yang module name: aaa-authz-service-impl yang module local name: aaa-authz-service
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 29 15:46:56 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.aaa_authz.srv;
public class Policies {
    private org.opendaylight.controller.config.api.DependencyResolver dependencyResolver;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType service;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType resource;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ActionType action;

    private org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType role;

    public Policies () {
        super();
    }

    public void injectDependencyResolver(org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        this.dependencyResolver = dependencyResolver;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType getService() {
        return service;
    }

    public void setService(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ServiceType service) {
        this.service = service;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType getResource() {
        return resource;
    }

    public void setResource(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ResourceType resource) {
        this.resource = resource;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ActionType getAction() {
        return action;
    }

    public void setAction(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.ActionType action) {
        this.action = action;
    }

    public org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType getRole() {
        return role;
    }

    public void setRole(org.opendaylight.yang.gen.v1.urn.aaa.yang.authz.ds.rev140722.RoleType role) {
        this.role = role;
    }

}
