title Credential Authentication Sequence

# This walks through the credential authentication use case where a credential 
# (typically username/password) is used to authenticate directly with the ODL 
# controller. 

Client -> ServletContainer: request access token
note right of Client
(credentials, scope=domain)
end note
ServletContainer -> TokenEndpoint: credentials, domain
TokenEndpoint -> CredentialAuth: authenticate(Credentials, domain)
CredentialAuth -> TokenEndpoint: Claim
note left of CredentialAuth
(user/domain/roles)
end note
TokenEndpoint -> TokenEndpoint: createToken
TokenEndpoint -> Client: access token